---         
apiVersion: v1
kind: Service
metadata:
  name: {{ template "optimusddc.name" . }}-{{ .Values.frontEnd.serviceName }}
  labels:
    app: {{ template "optimusddc.name" . }}
    run: {{ .Chart.Name }}-{{ .Values.frontEnd.serviceName }}
    component: {{ .Values.frontEnd.serviceName }}
    chart: {{ template "optimusddc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.frontEnd.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end}}   
spec:
  type: {{ .Values.frontEnd.serviceType }}
  selector:
    app: {{ template "optimusddc.name" . }}
    component: {{ .Values.frontEnd.serviceName }}
    release: {{ .Release.Name }}
  ports:
    - name: {{ .Chart.Name }}-{{ .Values.frontEnd.serviceName }}-{{ .Values.environment }}-http
      port: 5000
      targetPort: 5000
