---  
apiVersion: v1
kind: Service
metadata:
  name: {{ template "optimusddc.name" . }}-{{ .Values.metadata.serviceName }}
  labels:
    app: {{ template "optimusddc.name" . }}
    run: {{ .Chart.Name }}-{{ .Values.metadata.serviceName }}
    component: {{ .Values.metadata.serviceName }}
    chart: {{ template "optimusddc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.metadata.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end}}           
spec:
  type: {{ .Values.metadata.serviceType }}
  selector:
    app: {{ template "optimusddc.name" . }}
    component: {{ .Values.metadata.serviceName }}
    release: {{ .Release.Name }}
  ports:
    - name: {{ .Chart.Name }}-{{ .Values.metadata.serviceName }}-{{ .Values.environment }}-http
      port: 5002
      targetPort: 5002
